import sys

autogen_comments = '''/*
Autogenerated file - DO NOT EDIT
This file was generated by the //buildtools/generate_shader_include.py.
*/

'''

def generate_cpp_code(replace_values):
    code_template = '''#include <essl/{0}.bin.h>
#include <glsl/{0}.bin.h>
#include <spv/{0}.bin.h>
#if defined(_WIN32)
#include <dx11/{0}.bin.h>
#endif  //  defined(_WIN32)
#if __APPLE__
#include <mtl/{0}.bin.h>
#endif  // __APPLE__

const bgfx::EmbeddedShader k_{1} = BGFX_EMBEDDED_SHADER({1});
'''

    generated_code = autogen_comments
    for value in replace_values:
        fname = value.find('.')
        generated_code += code_template.format(value, value[:fname]) + "\n\n"

    return generated_code

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python generate_cpp_code.py output_file value1 value2 value3 ...")
        sys.exit(1)

    output_file = sys.argv[1]
    replace_values = sys.argv[2].split()
    print(replace_values)
    cpp_code = generate_cpp_code(replace_values)

    with open(output_file, 'w') as f:
        f.write(cpp_code)
