import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--header", action="store_true", help="Generate header file")
parser.add_argument("--body", action="store_true", help="Generate defined body file")

args = parser.parse_args()

autogen_comments = '''/*
Autogenerated file - DO NOT EDIT
This file was generated by the //gpu/gles2/build_gles2_command_buffer.py.
*/
\n\n'''

if args.header:
  with open("gles2_commands.txt", "r") as file:
    functions = file.readlines()
  functions = [function.strip() for function in functions]
  converted_functions = []
  converted_functions.append(autogen_comments)
  for function in functions:
    converted_functions.append("_PFN" + function.upper() + "PROC " + function + " = nullptr;\n\n")
  with open("gles2_command_buffer_header_autogen.h", "w") as file:
    file.writelines(converted_functions)

elif args.body:
  with open("gles2_commands.txt", "r") as file:
    functions = file.readlines()
  functions = [function.strip() for function in functions]
  converted_functions = []
  converted_functions.append(autogen_comments)
  for function in functions:
    converted_functions.append("{} = static_cast<{}>(GetProc(\"{}\"));\n\n".format(function, "_PFN" + function.upper() + "PROC", function))
  with open("gles2_command_buffer_autogen.cc", "w") as file:
    file.writelines(converted_functions)
