/*
Autogenerated file - DO NOT EDIT
This file was generated by the //gpu/gles2/build_gles2_command_buffer.py.
*/


_PFNGLACTIVETEXTUREPROC ActiveTexture = nullptr;

_PFNGLATTACHSHADERPROC AttachShader = nullptr;

_PFNGLBINDATTRIBLOCATIONPROC BindAttribLocation = nullptr;

_PFNGLBINDBUFFERPROC BindBuffer = nullptr;

_PFNGLBINDFRAMEBUFFERPROC BindFramebuffer = nullptr;

_PFNGLBINDRENDERBUFFERPROC BindRenderbuffer = nullptr;

_PFNGLBINDTEXTUREPROC BindTexture = nullptr;

_PFNGLBLENDCOLORPROC BlendColor = nullptr;

_PFNGLBLENDEQUATIONPROC BlendEquation = nullptr;

_PFNGLBLENDEQUATIONSEPARATEPROC BlendEquationSeparate = nullptr;

_PFNGLBLENDFUNCPROC BlendFunc = nullptr;

_PFNGLBLENDFUNCSEPARATEPROC BlendFuncSeparate = nullptr;

_PFNGLBUFFERDATAPROC BufferData = nullptr;

_PFNGLBUFFERSUBDATAPROC BufferSubData = nullptr;

_PFNGLCHECKFRAMEBUFFERSTATUSPROC CheckFramebufferStatus = nullptr;

_PFNGLCLEARPROC Clear = nullptr;

_PFNGLCLEARCOLORPROC ClearColor = nullptr;

_PFNGLCLEARDEPTHFPROC ClearDepthf = nullptr;

_PFNGLCLEARSTENCILPROC ClearStencil = nullptr;

_PFNGLCOLORMASKPROC ColorMask = nullptr;

_PFNGLCOMPILESHADERPROC CompileShader = nullptr;

_PFNGLCOMPRESSEDTEXIMAGE2DPROC CompressedTexImage2D = nullptr;

_PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC CompressedTexSubImage2D = nullptr;

_PFNGLCOPYTEXIMAGE2DPROC CopyTexImage2D = nullptr;

_PFNGLCOPYTEXSUBIMAGE2DPROC CopyTexSubImage2D = nullptr;

_PFNGLCREATEPROGRAMPROC CreateProgram = nullptr;

_PFNGLCREATESHADERPROC CreateShader = nullptr;

_PFNGLCULLFACEPROC CullFace = nullptr;

_PFNGLDELETEBUFFERSPROC DeleteBuffers = nullptr;

_PFNGLDELETEFRAMEBUFFERSPROC DeleteFramebuffers = nullptr;

_PFNGLDELETEPROGRAMPROC DeleteProgram = nullptr;

_PFNGLDELETERENDERBUFFERSPROC DeleteRenderbuffers = nullptr;

_PFNGLDELETESHADERPROC DeleteShader = nullptr;

_PFNGLDELETETEXTURESPROC DeleteTextures = nullptr;

_PFNGLDEPTHFUNCPROC DepthFunc = nullptr;

_PFNGLDEPTHMASKPROC DepthMask = nullptr;

_PFNGLDEPTHRANGEFPROC DepthRangef = nullptr;

_PFNGLDETACHSHADERPROC DetachShader = nullptr;

_PFNGLDISABLEPROC Disable = nullptr;

_PFNGLDISABLEVERTEXATTRIBARRAYPROC DisableVertexAttribArray = nullptr;

_PFNGLDRAWARRAYSPROC DrawArrays = nullptr;

_PFNGLDRAWELEMENTSPROC DrawElements = nullptr;

_PFNGLENABLEPROC Enable = nullptr;

_PFNGLENABLEVERTEXATTRIBARRAYPROC EnableVertexAttribArray = nullptr;

_PFNGLFINISHPROC Finish = nullptr;

_PFNGLFLUSHPROC Flush = nullptr;

_PFNGLFRAMEBUFFERRENDERBUFFERPROC FramebufferRenderbuffer = nullptr;

_PFNGLFRAMEBUFFERTEXTURE2DPROC FramebufferTexture2D = nullptr;

_PFNGLFRONTFACEPROC FrontFace = nullptr;

_PFNGLGENBUFFERSPROC GenBuffers = nullptr;

_PFNGLGENERATEMIPMAPPROC GenerateMipmap = nullptr;

_PFNGLGENFRAMEBUFFERSPROC GenFramebuffers = nullptr;

_PFNGLGENRENDERBUFFERSPROC GenRenderbuffers = nullptr;

_PFNGLGENTEXTURESPROC GenTextures = nullptr;

_PFNGLGETACTIVEATTRIBPROC GetActiveAttrib = nullptr;

_PFNGLGETACTIVEUNIFORMPROC GetActiveUniform = nullptr;

_PFNGLGETATTACHEDSHADERSPROC GetAttachedShaders = nullptr;

_PFNGLGETATTRIBLOCATIONPROC GetAttribLocation = nullptr;

_PFNGLGETBOOLEANVPROC GetBooleanv = nullptr;

_PFNGLGETBUFFERPARAMETERIVPROC GetBufferParameteriv = nullptr;

_PFNGLGETERRORPROC GetError = nullptr;

_PFNGLGETFLOATVPROC GetFloatv = nullptr;

_PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC GetFramebufferAttachmentParameteriv = nullptr;

_PFNGLGETINTEGERVPROC GetIntegerv = nullptr;

_PFNGLGETPROGRAMIVPROC GetProgramiv = nullptr;

_PFNGLGETPROGRAMINFOLOGPROC GetProgramInfoLog = nullptr;

_PFNGLGETRENDERBUFFERPARAMETERIVPROC GetRenderbufferParameteriv = nullptr;

_PFNGLGETSHADERIVPROC GetShaderiv = nullptr;

_PFNGLGETSHADERINFOLOGPROC GetShaderInfoLog = nullptr;

_PFNGLGETSHADERPRECISIONFORMATPROC GetShaderPrecisionFormat = nullptr;

_PFNGLGETSHADERSOURCEPROC GetShaderSource = nullptr;

_PFNGLGETSTRINGPROC GetString = nullptr;

_PFNGLGETTEXPARAMETERFVPROC GetTexParameterfv = nullptr;

_PFNGLGETTEXPARAMETERIVPROC GetTexParameteriv = nullptr;

_PFNGLGETUNIFORMFVPROC GetUniformfv = nullptr;

_PFNGLGETUNIFORMIVPROC GetUniformiv = nullptr;

_PFNGLGETUNIFORMLOCATIONPROC GetUniformLocation = nullptr;

_PFNGLGETVERTEXATTRIBFVPROC GetVertexAttribfv = nullptr;

_PFNGLGETVERTEXATTRIBIVPROC GetVertexAttribiv = nullptr;

_PFNGLGETVERTEXATTRIBPOINTERVPROC GetVertexAttribPointerv = nullptr;

_PFNGLHINTPROC Hint = nullptr;

_PFNGLISBUFFERPROC IsBuffer = nullptr;

_PFNGLISENABLEDPROC IsEnabled = nullptr;

_PFNGLISFRAMEBUFFERPROC IsFramebuffer = nullptr;

_PFNGLISPROGRAMPROC IsProgram = nullptr;

_PFNGLISRENDERBUFFERPROC IsRenderbuffer = nullptr;

_PFNGLISSHADERPROC IsShader = nullptr;

_PFNGLISTEXTUREPROC IsTexture = nullptr;

_PFNGLLINEWIDTHPROC LineWidth = nullptr;

_PFNGLLINKPROGRAMPROC LinkProgram = nullptr;

_PFNGLPIXELSTOREIPROC PixelStorei = nullptr;

_PFNGLPOLYGONOFFSETPROC PolygonOffset = nullptr;

_PFNGLREADPIXELSPROC ReadPixels = nullptr;

_PFNGLRELEASESHADERCOMPILERPROC ReleaseShaderCompiler = nullptr;

_PFNGLRENDERBUFFERSTORAGEPROC RenderbufferStorage = nullptr;

_PFNGLSAMPLECOVERAGEPROC SampleCoverage = nullptr;

_PFNGLSCISSORPROC Scissor = nullptr;

_PFNGLSHADERBINARYPROC ShaderBinary = nullptr;

_PFNGLSHADERSOURCEPROC ShaderSource = nullptr;

_PFNGLSTENCILFUNCPROC StencilFunc = nullptr;

_PFNGLSTENCILFUNCSEPARATEPROC StencilFuncSeparate = nullptr;

_PFNGLSTENCILMASKPROC StencilMask = nullptr;

_PFNGLSTENCILMASKSEPARATEPROC StencilMaskSeparate = nullptr;

_PFNGLSTENCILOPPROC StencilOp = nullptr;

_PFNGLSTENCILOPSEPARATEPROC StencilOpSeparate = nullptr;

_PFNGLTEXIMAGE2DPROC TexImage2D = nullptr;

_PFNGLTEXPARAMETERFPROC TexParameterf = nullptr;

_PFNGLTEXPARAMETERFVPROC TexParameterfv = nullptr;

_PFNGLTEXPARAMETERIPROC TexParameteri = nullptr;

_PFNGLTEXPARAMETERIVPROC TexParameteriv = nullptr;

_PFNGLTEXSUBIMAGE2DPROC TexSubImage2D = nullptr;

_PFNGLUNIFORM1FPROC Uniform1f = nullptr;

_PFNGLUNIFORM1FVPROC Uniform1fv = nullptr;

_PFNGLUNIFORM1IPROC Uniform1i = nullptr;

_PFNGLUNIFORM1IVPROC Uniform1iv = nullptr;

_PFNGLUNIFORM2FPROC Uniform2f = nullptr;

_PFNGLUNIFORM2FVPROC Uniform2fv = nullptr;

_PFNGLUNIFORM2IPROC Uniform2i = nullptr;

_PFNGLUNIFORM2IVPROC Uniform2iv = nullptr;

_PFNGLUNIFORM3FPROC Uniform3f = nullptr;

_PFNGLUNIFORM3FVPROC Uniform3fv = nullptr;

_PFNGLUNIFORM3IPROC Uniform3i = nullptr;

_PFNGLUNIFORM3IVPROC Uniform3iv = nullptr;

_PFNGLUNIFORM4FPROC Uniform4f = nullptr;

_PFNGLUNIFORM4FVPROC Uniform4fv = nullptr;

_PFNGLUNIFORM4IPROC Uniform4i = nullptr;

_PFNGLUNIFORM4IVPROC Uniform4iv = nullptr;

_PFNGLUNIFORMMATRIX2FVPROC UniformMatrix2fv = nullptr;

_PFNGLUNIFORMMATRIX3FVPROC UniformMatrix3fv = nullptr;

_PFNGLUNIFORMMATRIX4FVPROC UniformMatrix4fv = nullptr;

_PFNGLUSEPROGRAMPROC UseProgram = nullptr;

_PFNGLVALIDATEPROGRAMPROC ValidateProgram = nullptr;

_PFNGLVERTEXATTRIB1FPROC VertexAttrib1f = nullptr;

_PFNGLVERTEXATTRIB1FVPROC VertexAttrib1fv = nullptr;

_PFNGLVERTEXATTRIB2FPROC VertexAttrib2f = nullptr;

_PFNGLVERTEXATTRIB2FVPROC VertexAttrib2fv = nullptr;

_PFNGLVERTEXATTRIB3FPROC VertexAttrib3f = nullptr;

_PFNGLVERTEXATTRIB3FVPROC VertexAttrib3fv = nullptr;

_PFNGLVERTEXATTRIB4FPROC VertexAttrib4f = nullptr;

_PFNGLVERTEXATTRIB4FVPROC VertexAttrib4fv = nullptr;

_PFNGLVERTEXATTRIBPOINTERPROC VertexAttribPointer = nullptr;

_PFNGLVIEWPORTPROC Viewport = nullptr;

_PFNGLBINDVERTEXARRAYPROC BindVertexArray = nullptr;

_PFNGLDELETEVERTEXARRAYSPROC DeleteVertexArrays = nullptr;

_PFNGLGENVERTEXARRAYSPROC GenVertexArrays = nullptr;

_PFNGLISVERTEXARRAYPROC IsVertexArray = nullptr;

