/*
Autogenerated file - DO NOT EDIT
This file was generated by the //gpu/gles2/build_gles2_command_buffer.py.
*/


_PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers = nullptr;

_PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers = nullptr;

_PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer = nullptr;

_PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D = nullptr;

