/*
Autogenerated file - DO NOT EDIT
This file was generated by the //gpu/gles2/build_gles2_command_buffer.py.
*/


_PFNGLGETSTRINGPROC glGetString = nullptr;

_PFNGLGETERRORPROC glGetError = nullptr;

_PFNGLCLEARPROC glClear = nullptr;

_PFNGLCLEARCOLORPROC glClearColor = nullptr;

_PFNGLGETINTEGERVPROC glGetIntegerv = nullptr;

_PFNGLPIXELSTOREIPROC glPixelStorei = nullptr;

_PFNGLREADPIXELSPROC glReadPixels = nullptr;

_PFNGLENABLEPROC glEnable = nullptr;

_PFNGLDISABLEPROC glDisable = nullptr;

_PFNGLSCISSORPROC glScissor = nullptr;

_PFNGLVIEWPORTPROC glViewport = nullptr;

_PFNGLBLENDFUNCPROC glBlendFunc = nullptr;

_PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate = nullptr;

_PFNGLBLENDEQUATIONPROC glBlendEquation = nullptr;

_PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate = nullptr;

_PFNGLDRAWARRAYSPROC glDrawArrays = nullptr;

_PFNGLDRAWELEMENTSPROC glDrawElements = nullptr;

_PFNGLGENBUFFERSPROC glGenBuffers = nullptr;

_PFNGLDELETEBUFFERSPROC glDeleteBuffers = nullptr;

_PFNGLBINDBUFFERPROC glBindBuffer = nullptr;

_PFNGLBUFFERDATAPROC glBufferData = nullptr;

_PFNGLBUFFERSUBDATAPROC glBufferSubData = nullptr;

_PFNGLGENTEXTURESPROC glGenTextures = nullptr;

_PFNGLDELETETEXTURESPROC glDeleteTextures = nullptr;

_PFNGLBINDTEXTUREPROC glBindTexture = nullptr;

_PFNGLTEXIMAGE2DPROC glTexImage2D = nullptr;

_PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D = nullptr;

_PFNGLTEXPARAMETERFPROC glTexParameterf = nullptr;

_PFNGLTEXPARAMETERFVPROC glTexParameterfv = nullptr;

_PFNGLTEXPARAMETERIPROC glTexParameteri = nullptr;

_PFNGLTEXPARAMETERIVPROC glTexParameteriv = nullptr;

_PFNGLACTIVETEXTUREPROC glActiveTexture = nullptr;

_PFNGLCREATESHADERPROC glCreateShader = nullptr;

_PFNGLDELETESHADERPROC glDeleteShader = nullptr;

_PFNGLCOMPILESHADERPROC glCompileShader = nullptr;

_PFNGLSHADERSOURCEPROC glShaderSource = nullptr;

_PFNGLATTACHSHADERPROC glAttachShader = nullptr;

_PFNGLGETSHADERIVPROC glGetShaderiv = nullptr;

_PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = nullptr;

_PFNGLCREATEPROGRAMPROC glCreateProgram = nullptr;

_PFNGLDELETEPROGRAMPROC glDeleteProgram = nullptr;

_PFNGLUSEPROGRAMPROC glUseProgram = nullptr;

_PFNGLLINKPROGRAMPROC glLinkProgram = nullptr;

_PFNGLGETPROGRAMIVPROC glGetProgramiv = nullptr;

_PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = nullptr;

_PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = nullptr;

_PFNGLUNIFORM1FPROC glUniform1f = nullptr;

_PFNGLUNIFORM1FVPROC glUniform1fv = nullptr;

_PFNGLUNIFORM1IPROC glUniform1i = nullptr;

_PFNGLUNIFORM1IVPROC glUniform1iv = nullptr;

_PFNGLUNIFORM2FPROC glUniform2f = nullptr;

_PFNGLUNIFORM2FVPROC glUniform2fv = nullptr;

_PFNGLUNIFORM2IPROC glUniform2i = nullptr;

_PFNGLUNIFORM2IVPROC glUniform2iv = nullptr;

_PFNGLUNIFORM3FPROC glUniform3f = nullptr;

_PFNGLUNIFORM3FVPROC glUniform3fv = nullptr;

_PFNGLUNIFORM3IPROC glUniform3i = nullptr;

_PFNGLUNIFORM3IVPROC glUniform3iv = nullptr;

_PFNGLUNIFORM4FPROC glUniform4f = nullptr;

_PFNGLUNIFORM4FVPROC glUniform4fv = nullptr;

_PFNGLUNIFORM4IPROC glUniform4i = nullptr;

_PFNGLUNIFORM4IVPROC glUniform4iv = nullptr;

_PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv = nullptr;

_PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv = nullptr;

_PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv = nullptr;

_PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation = nullptr;

_PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = nullptr;

_PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = nullptr;

_PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = nullptr;

