/*
Autogenerated file - DO NOT EDIT
This file was generated by the //gpu/gles2/build_gles2_command_buffer.py.
*/


ActiveTexture = static_cast<_PFNGLACTIVETEXTUREPROC>(GetProc("ActiveTexture"));

AttachShader = static_cast<_PFNGLATTACHSHADERPROC>(GetProc("AttachShader"));

BindAttribLocation = static_cast<_PFNGLBINDATTRIBLOCATIONPROC>(GetProc("BindAttribLocation"));

BindBuffer = static_cast<_PFNGLBINDBUFFERPROC>(GetProc("BindBuffer"));

BindFramebuffer = static_cast<_PFNGLBINDFRAMEBUFFERPROC>(GetProc("BindFramebuffer"));

BindRenderbuffer = static_cast<_PFNGLBINDRENDERBUFFERPROC>(GetProc("BindRenderbuffer"));

BindTexture = static_cast<_PFNGLBINDTEXTUREPROC>(GetProc("BindTexture"));

BlendColor = static_cast<_PFNGLBLENDCOLORPROC>(GetProc("BlendColor"));

BlendEquation = static_cast<_PFNGLBLENDEQUATIONPROC>(GetProc("BlendEquation"));

BlendEquationSeparate = static_cast<_PFNGLBLENDEQUATIONSEPARATEPROC>(GetProc("BlendEquationSeparate"));

BlendFunc = static_cast<_PFNGLBLENDFUNCPROC>(GetProc("BlendFunc"));

BlendFuncSeparate = static_cast<_PFNGLBLENDFUNCSEPARATEPROC>(GetProc("BlendFuncSeparate"));

BufferData = static_cast<_PFNGLBUFFERDATAPROC>(GetProc("BufferData"));

BufferSubData = static_cast<_PFNGLBUFFERSUBDATAPROC>(GetProc("BufferSubData"));

CheckFramebufferStatus = static_cast<_PFNGLCHECKFRAMEBUFFERSTATUSPROC>(GetProc("CheckFramebufferStatus"));

Clear = static_cast<_PFNGLCLEARPROC>(GetProc("Clear"));

ClearColor = static_cast<_PFNGLCLEARCOLORPROC>(GetProc("ClearColor"));

ClearDepthf = static_cast<_PFNGLCLEARDEPTHFPROC>(GetProc("ClearDepthf"));

ClearStencil = static_cast<_PFNGLCLEARSTENCILPROC>(GetProc("ClearStencil"));

ColorMask = static_cast<_PFNGLCOLORMASKPROC>(GetProc("ColorMask"));

CompileShader = static_cast<_PFNGLCOMPILESHADERPROC>(GetProc("CompileShader"));

CompressedTexImage2D = static_cast<_PFNGLCOMPRESSEDTEXIMAGE2DPROC>(GetProc("CompressedTexImage2D"));

CompressedTexSubImage2D = static_cast<_PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC>(GetProc("CompressedTexSubImage2D"));

CopyTexImage2D = static_cast<_PFNGLCOPYTEXIMAGE2DPROC>(GetProc("CopyTexImage2D"));

CopyTexSubImage2D = static_cast<_PFNGLCOPYTEXSUBIMAGE2DPROC>(GetProc("CopyTexSubImage2D"));

CreateProgram = static_cast<_PFNGLCREATEPROGRAMPROC>(GetProc("CreateProgram"));

CreateShader = static_cast<_PFNGLCREATESHADERPROC>(GetProc("CreateShader"));

CullFace = static_cast<_PFNGLCULLFACEPROC>(GetProc("CullFace"));

DeleteBuffers = static_cast<_PFNGLDELETEBUFFERSPROC>(GetProc("DeleteBuffers"));

DeleteFramebuffers = static_cast<_PFNGLDELETEFRAMEBUFFERSPROC>(GetProc("DeleteFramebuffers"));

DeleteProgram = static_cast<_PFNGLDELETEPROGRAMPROC>(GetProc("DeleteProgram"));

DeleteRenderbuffers = static_cast<_PFNGLDELETERENDERBUFFERSPROC>(GetProc("DeleteRenderbuffers"));

DeleteShader = static_cast<_PFNGLDELETESHADERPROC>(GetProc("DeleteShader"));

DeleteTextures = static_cast<_PFNGLDELETETEXTURESPROC>(GetProc("DeleteTextures"));

DepthFunc = static_cast<_PFNGLDEPTHFUNCPROC>(GetProc("DepthFunc"));

DepthMask = static_cast<_PFNGLDEPTHMASKPROC>(GetProc("DepthMask"));

DepthRangef = static_cast<_PFNGLDEPTHRANGEFPROC>(GetProc("DepthRangef"));

DetachShader = static_cast<_PFNGLDETACHSHADERPROC>(GetProc("DetachShader"));

Disable = static_cast<_PFNGLDISABLEPROC>(GetProc("Disable"));

DisableVertexAttribArray = static_cast<_PFNGLDISABLEVERTEXATTRIBARRAYPROC>(GetProc("DisableVertexAttribArray"));

DrawArrays = static_cast<_PFNGLDRAWARRAYSPROC>(GetProc("DrawArrays"));

DrawElements = static_cast<_PFNGLDRAWELEMENTSPROC>(GetProc("DrawElements"));

Enable = static_cast<_PFNGLENABLEPROC>(GetProc("Enable"));

EnableVertexAttribArray = static_cast<_PFNGLENABLEVERTEXATTRIBARRAYPROC>(GetProc("EnableVertexAttribArray"));

Finish = static_cast<_PFNGLFINISHPROC>(GetProc("Finish"));

Flush = static_cast<_PFNGLFLUSHPROC>(GetProc("Flush"));

FramebufferRenderbuffer = static_cast<_PFNGLFRAMEBUFFERRENDERBUFFERPROC>(GetProc("FramebufferRenderbuffer"));

FramebufferTexture2D = static_cast<_PFNGLFRAMEBUFFERTEXTURE2DPROC>(GetProc("FramebufferTexture2D"));

FrontFace = static_cast<_PFNGLFRONTFACEPROC>(GetProc("FrontFace"));

GenBuffers = static_cast<_PFNGLGENBUFFERSPROC>(GetProc("GenBuffers"));

GenerateMipmap = static_cast<_PFNGLGENERATEMIPMAPPROC>(GetProc("GenerateMipmap"));

GenFramebuffers = static_cast<_PFNGLGENFRAMEBUFFERSPROC>(GetProc("GenFramebuffers"));

GenRenderbuffers = static_cast<_PFNGLGENRENDERBUFFERSPROC>(GetProc("GenRenderbuffers"));

GenTextures = static_cast<_PFNGLGENTEXTURESPROC>(GetProc("GenTextures"));

GetActiveAttrib = static_cast<_PFNGLGETACTIVEATTRIBPROC>(GetProc("GetActiveAttrib"));

GetActiveUniform = static_cast<_PFNGLGETACTIVEUNIFORMPROC>(GetProc("GetActiveUniform"));

GetAttachedShaders = static_cast<_PFNGLGETATTACHEDSHADERSPROC>(GetProc("GetAttachedShaders"));

GetAttribLocation = static_cast<_PFNGLGETATTRIBLOCATIONPROC>(GetProc("GetAttribLocation"));

GetBooleanv = static_cast<_PFNGLGETBOOLEANVPROC>(GetProc("GetBooleanv"));

GetBufferParameteriv = static_cast<_PFNGLGETBUFFERPARAMETERIVPROC>(GetProc("GetBufferParameteriv"));

GetError = static_cast<_PFNGLGETERRORPROC>(GetProc("GetError"));

GetFloatv = static_cast<_PFNGLGETFLOATVPROC>(GetProc("GetFloatv"));

GetFramebufferAttachmentParameteriv = static_cast<_PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC>(GetProc("GetFramebufferAttachmentParameteriv"));

GetIntegerv = static_cast<_PFNGLGETINTEGERVPROC>(GetProc("GetIntegerv"));

GetProgramiv = static_cast<_PFNGLGETPROGRAMIVPROC>(GetProc("GetProgramiv"));

GetProgramInfoLog = static_cast<_PFNGLGETPROGRAMINFOLOGPROC>(GetProc("GetProgramInfoLog"));

GetRenderbufferParameteriv = static_cast<_PFNGLGETRENDERBUFFERPARAMETERIVPROC>(GetProc("GetRenderbufferParameteriv"));

GetShaderiv = static_cast<_PFNGLGETSHADERIVPROC>(GetProc("GetShaderiv"));

GetShaderInfoLog = static_cast<_PFNGLGETSHADERINFOLOGPROC>(GetProc("GetShaderInfoLog"));

GetShaderPrecisionFormat = static_cast<_PFNGLGETSHADERPRECISIONFORMATPROC>(GetProc("GetShaderPrecisionFormat"));

GetShaderSource = static_cast<_PFNGLGETSHADERSOURCEPROC>(GetProc("GetShaderSource"));

GetString = static_cast<_PFNGLGETSTRINGPROC>(GetProc("GetString"));

GetTexParameterfv = static_cast<_PFNGLGETTEXPARAMETERFVPROC>(GetProc("GetTexParameterfv"));

GetTexParameteriv = static_cast<_PFNGLGETTEXPARAMETERIVPROC>(GetProc("GetTexParameteriv"));

GetUniformfv = static_cast<_PFNGLGETUNIFORMFVPROC>(GetProc("GetUniformfv"));

GetUniformiv = static_cast<_PFNGLGETUNIFORMIVPROC>(GetProc("GetUniformiv"));

GetUniformLocation = static_cast<_PFNGLGETUNIFORMLOCATIONPROC>(GetProc("GetUniformLocation"));

GetVertexAttribfv = static_cast<_PFNGLGETVERTEXATTRIBFVPROC>(GetProc("GetVertexAttribfv"));

GetVertexAttribiv = static_cast<_PFNGLGETVERTEXATTRIBIVPROC>(GetProc("GetVertexAttribiv"));

GetVertexAttribPointerv = static_cast<_PFNGLGETVERTEXATTRIBPOINTERVPROC>(GetProc("GetVertexAttribPointerv"));

Hint = static_cast<_PFNGLHINTPROC>(GetProc("Hint"));

IsBuffer = static_cast<_PFNGLISBUFFERPROC>(GetProc("IsBuffer"));

IsEnabled = static_cast<_PFNGLISENABLEDPROC>(GetProc("IsEnabled"));

IsFramebuffer = static_cast<_PFNGLISFRAMEBUFFERPROC>(GetProc("IsFramebuffer"));

IsProgram = static_cast<_PFNGLISPROGRAMPROC>(GetProc("IsProgram"));

IsRenderbuffer = static_cast<_PFNGLISRENDERBUFFERPROC>(GetProc("IsRenderbuffer"));

IsShader = static_cast<_PFNGLISSHADERPROC>(GetProc("IsShader"));

IsTexture = static_cast<_PFNGLISTEXTUREPROC>(GetProc("IsTexture"));

LineWidth = static_cast<_PFNGLLINEWIDTHPROC>(GetProc("LineWidth"));

LinkProgram = static_cast<_PFNGLLINKPROGRAMPROC>(GetProc("LinkProgram"));

PixelStorei = static_cast<_PFNGLPIXELSTOREIPROC>(GetProc("PixelStorei"));

PolygonOffset = static_cast<_PFNGLPOLYGONOFFSETPROC>(GetProc("PolygonOffset"));

ReadPixels = static_cast<_PFNGLREADPIXELSPROC>(GetProc("ReadPixels"));

ReleaseShaderCompiler = static_cast<_PFNGLRELEASESHADERCOMPILERPROC>(GetProc("ReleaseShaderCompiler"));

RenderbufferStorage = static_cast<_PFNGLRENDERBUFFERSTORAGEPROC>(GetProc("RenderbufferStorage"));

SampleCoverage = static_cast<_PFNGLSAMPLECOVERAGEPROC>(GetProc("SampleCoverage"));

Scissor = static_cast<_PFNGLSCISSORPROC>(GetProc("Scissor"));

ShaderBinary = static_cast<_PFNGLSHADERBINARYPROC>(GetProc("ShaderBinary"));

ShaderSource = static_cast<_PFNGLSHADERSOURCEPROC>(GetProc("ShaderSource"));

StencilFunc = static_cast<_PFNGLSTENCILFUNCPROC>(GetProc("StencilFunc"));

StencilFuncSeparate = static_cast<_PFNGLSTENCILFUNCSEPARATEPROC>(GetProc("StencilFuncSeparate"));

StencilMask = static_cast<_PFNGLSTENCILMASKPROC>(GetProc("StencilMask"));

StencilMaskSeparate = static_cast<_PFNGLSTENCILMASKSEPARATEPROC>(GetProc("StencilMaskSeparate"));

StencilOp = static_cast<_PFNGLSTENCILOPPROC>(GetProc("StencilOp"));

StencilOpSeparate = static_cast<_PFNGLSTENCILOPSEPARATEPROC>(GetProc("StencilOpSeparate"));

TexImage2D = static_cast<_PFNGLTEXIMAGE2DPROC>(GetProc("TexImage2D"));

TexParameterf = static_cast<_PFNGLTEXPARAMETERFPROC>(GetProc("TexParameterf"));

TexParameterfv = static_cast<_PFNGLTEXPARAMETERFVPROC>(GetProc("TexParameterfv"));

TexParameteri = static_cast<_PFNGLTEXPARAMETERIPROC>(GetProc("TexParameteri"));

TexParameteriv = static_cast<_PFNGLTEXPARAMETERIVPROC>(GetProc("TexParameteriv"));

TexSubImage2D = static_cast<_PFNGLTEXSUBIMAGE2DPROC>(GetProc("TexSubImage2D"));

Uniform1f = static_cast<_PFNGLUNIFORM1FPROC>(GetProc("Uniform1f"));

Uniform1fv = static_cast<_PFNGLUNIFORM1FVPROC>(GetProc("Uniform1fv"));

Uniform1i = static_cast<_PFNGLUNIFORM1IPROC>(GetProc("Uniform1i"));

Uniform1iv = static_cast<_PFNGLUNIFORM1IVPROC>(GetProc("Uniform1iv"));

Uniform2f = static_cast<_PFNGLUNIFORM2FPROC>(GetProc("Uniform2f"));

Uniform2fv = static_cast<_PFNGLUNIFORM2FVPROC>(GetProc("Uniform2fv"));

Uniform2i = static_cast<_PFNGLUNIFORM2IPROC>(GetProc("Uniform2i"));

Uniform2iv = static_cast<_PFNGLUNIFORM2IVPROC>(GetProc("Uniform2iv"));

Uniform3f = static_cast<_PFNGLUNIFORM3FPROC>(GetProc("Uniform3f"));

Uniform3fv = static_cast<_PFNGLUNIFORM3FVPROC>(GetProc("Uniform3fv"));

Uniform3i = static_cast<_PFNGLUNIFORM3IPROC>(GetProc("Uniform3i"));

Uniform3iv = static_cast<_PFNGLUNIFORM3IVPROC>(GetProc("Uniform3iv"));

Uniform4f = static_cast<_PFNGLUNIFORM4FPROC>(GetProc("Uniform4f"));

Uniform4fv = static_cast<_PFNGLUNIFORM4FVPROC>(GetProc("Uniform4fv"));

Uniform4i = static_cast<_PFNGLUNIFORM4IPROC>(GetProc("Uniform4i"));

Uniform4iv = static_cast<_PFNGLUNIFORM4IVPROC>(GetProc("Uniform4iv"));

UniformMatrix2fv = static_cast<_PFNGLUNIFORMMATRIX2FVPROC>(GetProc("UniformMatrix2fv"));

UniformMatrix3fv = static_cast<_PFNGLUNIFORMMATRIX3FVPROC>(GetProc("UniformMatrix3fv"));

UniformMatrix4fv = static_cast<_PFNGLUNIFORMMATRIX4FVPROC>(GetProc("UniformMatrix4fv"));

UseProgram = static_cast<_PFNGLUSEPROGRAMPROC>(GetProc("UseProgram"));

ValidateProgram = static_cast<_PFNGLVALIDATEPROGRAMPROC>(GetProc("ValidateProgram"));

VertexAttrib1f = static_cast<_PFNGLVERTEXATTRIB1FPROC>(GetProc("VertexAttrib1f"));

VertexAttrib1fv = static_cast<_PFNGLVERTEXATTRIB1FVPROC>(GetProc("VertexAttrib1fv"));

VertexAttrib2f = static_cast<_PFNGLVERTEXATTRIB2FPROC>(GetProc("VertexAttrib2f"));

VertexAttrib2fv = static_cast<_PFNGLVERTEXATTRIB2FVPROC>(GetProc("VertexAttrib2fv"));

VertexAttrib3f = static_cast<_PFNGLVERTEXATTRIB3FPROC>(GetProc("VertexAttrib3f"));

VertexAttrib3fv = static_cast<_PFNGLVERTEXATTRIB3FVPROC>(GetProc("VertexAttrib3fv"));

VertexAttrib4f = static_cast<_PFNGLVERTEXATTRIB4FPROC>(GetProc("VertexAttrib4f"));

VertexAttrib4fv = static_cast<_PFNGLVERTEXATTRIB4FVPROC>(GetProc("VertexAttrib4fv"));

VertexAttribPointer = static_cast<_PFNGLVERTEXATTRIBPOINTERPROC>(GetProc("VertexAttribPointer"));

Viewport = static_cast<_PFNGLVIEWPORTPROC>(GetProc("Viewport"));

BindVertexArray = static_cast<_PFNGLBINDVERTEXARRAYPROC>(GetProc("BindVertexArray"));

DeleteVertexArrays = static_cast<_PFNGLDELETEVERTEXARRAYSPROC>(GetProc("DeleteVertexArrays"));

GenVertexArrays = static_cast<_PFNGLGENVERTEXARRAYSPROC>(GetProc("GenVertexArrays"));

IsVertexArray = static_cast<_PFNGLISVERTEXARRAYPROC>(GetProc("IsVertexArray"));

