/*
Autogenerated file - DO NOT EDIT
This file was generated by the //gpu/gles2/build_gles2_command_buffer.py.
*/


glGetString = static_cast<_PFNGLGETSTRINGPROC>(GetProc("glGetString"));

glGetError = static_cast<_PFNGLGETERRORPROC>(GetProc("glGetError"));

glClear = static_cast<_PFNGLCLEARPROC>(GetProc("glClear"));

glClearColor = static_cast<_PFNGLCLEARCOLORPROC>(GetProc("glClearColor"));

glGetIntegerv = static_cast<_PFNGLGETINTEGERVPROC>(GetProc("glGetIntegerv"));

glPixelStorei = static_cast<_PFNGLPIXELSTOREIPROC>(GetProc("glPixelStorei"));

glReadPixels = static_cast<_PFNGLREADPIXELSPROC>(GetProc("glReadPixels"));

glEnable = static_cast<_PFNGLENABLEPROC>(GetProc("glEnable"));

glDisable = static_cast<_PFNGLDISABLEPROC>(GetProc("glDisable"));

glScissor = static_cast<_PFNGLSCISSORPROC>(GetProc("glScissor"));

glViewport = static_cast<_PFNGLVIEWPORTPROC>(GetProc("glViewport"));

glBlendFunc = static_cast<_PFNGLBLENDFUNCPROC>(GetProc("glBlendFunc"));

glBlendFuncSeparate = static_cast<_PFNGLBLENDFUNCSEPARATEPROC>(GetProc("glBlendFuncSeparate"));

glBlendEquation = static_cast<_PFNGLBLENDEQUATIONPROC>(GetProc("glBlendEquation"));

glBlendEquationSeparate = static_cast<_PFNGLBLENDEQUATIONSEPARATEPROC>(GetProc("glBlendEquationSeparate"));

glDrawArrays = static_cast<_PFNGLDRAWARRAYSPROC>(GetProc("glDrawArrays"));

glDrawElements = static_cast<_PFNGLDRAWELEMENTSPROC>(GetProc("glDrawElements"));

glGenBuffers = static_cast<_PFNGLGENBUFFERSPROC>(GetProc("glGenBuffers"));

glDeleteBuffers = static_cast<_PFNGLDELETEBUFFERSPROC>(GetProc("glDeleteBuffers"));

glBindBuffer = static_cast<_PFNGLBINDBUFFERPROC>(GetProc("glBindBuffer"));

glBufferData = static_cast<_PFNGLBUFFERDATAPROC>(GetProc("glBufferData"));

glBufferSubData = static_cast<_PFNGLBUFFERSUBDATAPROC>(GetProc("glBufferSubData"));

glGenTextures = static_cast<_PFNGLGENTEXTURESPROC>(GetProc("glGenTextures"));

glDeleteTextures = static_cast<_PFNGLDELETETEXTURESPROC>(GetProc("glDeleteTextures"));

glBindTexture = static_cast<_PFNGLBINDTEXTUREPROC>(GetProc("glBindTexture"));

glTexImage2D = static_cast<_PFNGLTEXIMAGE2DPROC>(GetProc("glTexImage2D"));

glTexSubImage2D = static_cast<_PFNGLTEXSUBIMAGE2DPROC>(GetProc("glTexSubImage2D"));

glTexParameterf = static_cast<_PFNGLTEXPARAMETERFPROC>(GetProc("glTexParameterf"));

glTexParameterfv = static_cast<_PFNGLTEXPARAMETERFVPROC>(GetProc("glTexParameterfv"));

glTexParameteri = static_cast<_PFNGLTEXPARAMETERIPROC>(GetProc("glTexParameteri"));

glTexParameteriv = static_cast<_PFNGLTEXPARAMETERIVPROC>(GetProc("glTexParameteriv"));

glActiveTexture = static_cast<_PFNGLACTIVETEXTUREPROC>(GetProc("glActiveTexture"));

glCreateShader = static_cast<_PFNGLCREATESHADERPROC>(GetProc("glCreateShader"));

glDeleteShader = static_cast<_PFNGLDELETESHADERPROC>(GetProc("glDeleteShader"));

glCompileShader = static_cast<_PFNGLCOMPILESHADERPROC>(GetProc("glCompileShader"));

glShaderSource = static_cast<_PFNGLSHADERSOURCEPROC>(GetProc("glShaderSource"));

glAttachShader = static_cast<_PFNGLATTACHSHADERPROC>(GetProc("glAttachShader"));

glGetShaderiv = static_cast<_PFNGLGETSHADERIVPROC>(GetProc("glGetShaderiv"));

glGetShaderInfoLog = static_cast<_PFNGLGETSHADERINFOLOGPROC>(GetProc("glGetShaderInfoLog"));

glCreateProgram = static_cast<_PFNGLCREATEPROGRAMPROC>(GetProc("glCreateProgram"));

glDeleteProgram = static_cast<_PFNGLDELETEPROGRAMPROC>(GetProc("glDeleteProgram"));

glUseProgram = static_cast<_PFNGLUSEPROGRAMPROC>(GetProc("glUseProgram"));

glLinkProgram = static_cast<_PFNGLLINKPROGRAMPROC>(GetProc("glLinkProgram"));

glGetProgramiv = static_cast<_PFNGLGETPROGRAMIVPROC>(GetProc("glGetProgramiv"));

glGetProgramInfoLog = static_cast<_PFNGLGETPROGRAMINFOLOGPROC>(GetProc("glGetProgramInfoLog"));

glGetUniformLocation = static_cast<_PFNGLGETUNIFORMLOCATIONPROC>(GetProc("glGetUniformLocation"));

glUniform1f = static_cast<_PFNGLUNIFORM1FPROC>(GetProc("glUniform1f"));

glUniform1fv = static_cast<_PFNGLUNIFORM1FVPROC>(GetProc("glUniform1fv"));

glUniform1i = static_cast<_PFNGLUNIFORM1IPROC>(GetProc("glUniform1i"));

glUniform1iv = static_cast<_PFNGLUNIFORM1IVPROC>(GetProc("glUniform1iv"));

glUniform2f = static_cast<_PFNGLUNIFORM2FPROC>(GetProc("glUniform2f"));

glUniform2fv = static_cast<_PFNGLUNIFORM2FVPROC>(GetProc("glUniform2fv"));

glUniform2i = static_cast<_PFNGLUNIFORM2IPROC>(GetProc("glUniform2i"));

glUniform2iv = static_cast<_PFNGLUNIFORM2IVPROC>(GetProc("glUniform2iv"));

glUniform3f = static_cast<_PFNGLUNIFORM3FPROC>(GetProc("glUniform3f"));

glUniform3fv = static_cast<_PFNGLUNIFORM3FVPROC>(GetProc("glUniform3fv"));

glUniform3i = static_cast<_PFNGLUNIFORM3IPROC>(GetProc("glUniform3i"));

glUniform3iv = static_cast<_PFNGLUNIFORM3IVPROC>(GetProc("glUniform3iv"));

glUniform4f = static_cast<_PFNGLUNIFORM4FPROC>(GetProc("glUniform4f"));

glUniform4fv = static_cast<_PFNGLUNIFORM4FVPROC>(GetProc("glUniform4fv"));

glUniform4i = static_cast<_PFNGLUNIFORM4IPROC>(GetProc("glUniform4i"));

glUniform4iv = static_cast<_PFNGLUNIFORM4IVPROC>(GetProc("glUniform4iv"));

glUniformMatrix2fv = static_cast<_PFNGLUNIFORMMATRIX2FVPROC>(GetProc("glUniformMatrix2fv"));

glUniformMatrix3fv = static_cast<_PFNGLUNIFORMMATRIX3FVPROC>(GetProc("glUniformMatrix3fv"));

glUniformMatrix4fv = static_cast<_PFNGLUNIFORMMATRIX4FVPROC>(GetProc("glUniformMatrix4fv"));

glBindAttribLocation = static_cast<_PFNGLBINDATTRIBLOCATIONPROC>(GetProc("glBindAttribLocation"));

glEnableVertexAttribArray = static_cast<_PFNGLENABLEVERTEXATTRIBARRAYPROC>(GetProc("glEnableVertexAttribArray"));

glDisableVertexAttribArray = static_cast<_PFNGLDISABLEVERTEXATTRIBARRAYPROC>(GetProc("glDisableVertexAttribArray"));

glVertexAttribPointer = static_cast<_PFNGLVERTEXATTRIBPOINTERPROC>(GetProc("glVertexAttribPointer"));

