/*
Autogenerated file - DO NOT EDIT
This file was generated by the //gpu/gles2/build_gles2_command_buffer.py.
*/


glGenFramebuffers = static_cast<_PFNGLGENFRAMEBUFFERSPROC>(GetProc("glGenFramebuffers"));

glDeleteFramebuffers = static_cast<_PFNGLDELETEFRAMEBUFFERSPROC>(GetProc("glDeleteFramebuffers"));

glBindFramebuffer = static_cast<_PFNGLBINDFRAMEBUFFERPROC>(GetProc("glBindFramebuffer"));

glFramebufferTexture2D = static_cast<_PFNGLFRAMEBUFFERTEXTURE2DPROC>(GetProc("glFramebufferTexture2D"));

