/*
Autogenerated file - DO NOT EDIT
This file was generated by the //gpu/gles2/build_gles2_command_buffer.py.
*/


_PFNGLACTIVETEXTUREPROC glActiveTexture = nullptr;

_PFNGLATTACHSHADERPROC glAttachShader = nullptr;

_PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation = nullptr;

_PFNGLBINDBUFFERPROC glBindBuffer = nullptr;

_PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer = nullptr;

_PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer = nullptr;

_PFNGLBINDTEXTUREPROC glBindTexture = nullptr;

_PFNGLBLENDCOLORPROC glBlendColor = nullptr;

_PFNGLBLENDEQUATIONPROC glBlendEquation = nullptr;

_PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate = nullptr;

_PFNGLBLENDFUNCPROC glBlendFunc = nullptr;

_PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate = nullptr;

_PFNGLBUFFERDATAPROC glBufferData = nullptr;

_PFNGLBUFFERSUBDATAPROC glBufferSubData = nullptr;

_PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus = nullptr;

_PFNGLCLEARPROC glClear = nullptr;

_PFNGLCLEARCOLORPROC glClearColor = nullptr;

_PFNGLCLEARDEPTHFPROC glClearDepthf = nullptr;

_PFNGLCLEARSTENCILPROC glClearStencil = nullptr;

_PFNGLCOLORMASKPROC glColorMask = nullptr;

_PFNGLCOMPILESHADERPROC glCompileShader = nullptr;

_PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D = nullptr;

_PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D = nullptr;

_PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D = nullptr;

_PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D = nullptr;

_PFNGLCREATEPROGRAMPROC glCreateProgram = nullptr;

_PFNGLCREATESHADERPROC glCreateShader = nullptr;

_PFNGLCULLFACEPROC glCullFace = nullptr;

_PFNGLDELETEBUFFERSPROC glDeleteBuffers = nullptr;

_PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers = nullptr;

_PFNGLDELETEPROGRAMPROC glDeleteProgram = nullptr;

_PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers = nullptr;

_PFNGLDELETESHADERPROC glDeleteShader = nullptr;

_PFNGLDELETETEXTURESPROC glDeleteTextures = nullptr;

_PFNGLDEPTHFUNCPROC glDepthFunc = nullptr;

_PFNGLDEPTHMASKPROC glDepthMask = nullptr;

_PFNGLDEPTHRANGEFPROC glDepthRangef = nullptr;

_PFNGLDETACHSHADERPROC glDetachShader = nullptr;

_PFNGLDISABLEPROC glDisable = nullptr;

_PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = nullptr;

_PFNGLDRAWARRAYSPROC glDrawArrays = nullptr;

_PFNGLDRAWELEMENTSPROC glDrawElements = nullptr;

_PFNGLENABLEPROC glEnable = nullptr;

_PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = nullptr;

_PFNGLFINISHPROC glFinish = nullptr;

_PFNGLFLUSHPROC glFlush = nullptr;

_PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer = nullptr;

_PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D = nullptr;

_PFNGLFRONTFACEPROC glFrontFace = nullptr;

_PFNGLGENBUFFERSPROC glGenBuffers = nullptr;

_PFNGLGENERATEMIPMAPPROC glGenerateMipmap = nullptr;

_PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers = nullptr;

_PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers = nullptr;

_PFNGLGENTEXTURESPROC glGenTextures = nullptr;

_PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib = nullptr;

_PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform = nullptr;

_PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders = nullptr;

_PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation = nullptr;

_PFNGLGETBOOLEANVPROC glGetBooleanv = nullptr;

_PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv = nullptr;

_PFNGLGETERRORPROC glGetError = nullptr;

_PFNGLGETFLOATVPROC glGetFloatv = nullptr;

_PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv = nullptr;

_PFNGLGETINTEGERVPROC glGetIntegerv = nullptr;

_PFNGLGETPROGRAMIVPROC glGetProgramiv = nullptr;

_PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = nullptr;

_PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv = nullptr;

_PFNGLGETSHADERIVPROC glGetShaderiv = nullptr;

_PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = nullptr;

_PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat = nullptr;

_PFNGLGETSHADERSOURCEPROC glGetShaderSource = nullptr;

_PFNGLGETSTRINGPROC glGetString = nullptr;

_PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv = nullptr;

_PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv = nullptr;

_PFNGLGETUNIFORMFVPROC glGetUniformfv = nullptr;

_PFNGLGETUNIFORMIVPROC glGetUniformiv = nullptr;

_PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = nullptr;

_PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv = nullptr;

_PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv = nullptr;

_PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv = nullptr;

_PFNGLHINTPROC glHint = nullptr;

_PFNGLISBUFFERPROC glIsBuffer = nullptr;

_PFNGLISENABLEDPROC glIsEnabled = nullptr;

_PFNGLISFRAMEBUFFERPROC glIsFramebuffer = nullptr;

_PFNGLISPROGRAMPROC glIsProgram = nullptr;

_PFNGLISRENDERBUFFERPROC glIsRenderbuffer = nullptr;

_PFNGLISSHADERPROC glIsShader = nullptr;

_PFNGLISTEXTUREPROC glIsTexture = nullptr;

_PFNGLLINEWIDTHPROC glLineWidth = nullptr;

_PFNGLLINKPROGRAMPROC glLinkProgram = nullptr;

_PFNGLPIXELSTOREIPROC glPixelStorei = nullptr;

_PFNGLPOLYGONOFFSETPROC glPolygonOffset = nullptr;

_PFNGLREADPIXELSPROC glReadPixels = nullptr;

_PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler = nullptr;

_PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage = nullptr;

_PFNGLSAMPLECOVERAGEPROC glSampleCoverage = nullptr;

_PFNGLSCISSORPROC glScissor = nullptr;

_PFNGLSHADERBINARYPROC glShaderBinary = nullptr;

_PFNGLSHADERSOURCEPROC glShaderSource = nullptr;

_PFNGLSTENCILFUNCPROC glStencilFunc = nullptr;

_PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate = nullptr;

_PFNGLSTENCILMASKPROC glStencilMask = nullptr;

_PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate = nullptr;

_PFNGLSTENCILOPPROC glStencilOp = nullptr;

_PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate = nullptr;

_PFNGLTEXIMAGE2DPROC glTexImage2D = nullptr;

_PFNGLTEXPARAMETERFPROC glTexParameterf = nullptr;

_PFNGLTEXPARAMETERFVPROC glTexParameterfv = nullptr;

_PFNGLTEXPARAMETERIPROC glTexParameteri = nullptr;

_PFNGLTEXPARAMETERIVPROC glTexParameteriv = nullptr;

_PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D = nullptr;

_PFNGLUNIFORM1FPROC glUniform1f = nullptr;

_PFNGLUNIFORM1FVPROC glUniform1fv = nullptr;

_PFNGLUNIFORM1IPROC glUniform1i = nullptr;

_PFNGLUNIFORM1IVPROC glUniform1iv = nullptr;

_PFNGLUNIFORM2FPROC glUniform2f = nullptr;

_PFNGLUNIFORM2FVPROC glUniform2fv = nullptr;

_PFNGLUNIFORM2IPROC glUniform2i = nullptr;

_PFNGLUNIFORM2IVPROC glUniform2iv = nullptr;

_PFNGLUNIFORM3FPROC glUniform3f = nullptr;

_PFNGLUNIFORM3FVPROC glUniform3fv = nullptr;

_PFNGLUNIFORM3IPROC glUniform3i = nullptr;

_PFNGLUNIFORM3IVPROC glUniform3iv = nullptr;

_PFNGLUNIFORM4FPROC glUniform4f = nullptr;

_PFNGLUNIFORM4FVPROC glUniform4fv = nullptr;

_PFNGLUNIFORM4IPROC glUniform4i = nullptr;

_PFNGLUNIFORM4IVPROC glUniform4iv = nullptr;

_PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv = nullptr;

_PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv = nullptr;

_PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv = nullptr;

_PFNGLUSEPROGRAMPROC glUseProgram = nullptr;

_PFNGLVALIDATEPROGRAMPROC glValidateProgram = nullptr;

_PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f = nullptr;

_PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv = nullptr;

_PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f = nullptr;

_PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv = nullptr;

_PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f = nullptr;

_PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv = nullptr;

_PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f = nullptr;

_PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv = nullptr;

_PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = nullptr;

_PFNGLVIEWPORTPROC glViewport = nullptr;

