/*
Autogenerated file - DO NOT EDIT
This file was generated by the //gpu/gles2/build_gles2_command_buffer.py.
*/


glActiveTexture = static_cast<_PFNGLACTIVETEXTUREPROC>(GetProc("glActiveTexture"));

glAttachShader = static_cast<_PFNGLATTACHSHADERPROC>(GetProc("glAttachShader"));

glBindAttribLocation = static_cast<_PFNGLBINDATTRIBLOCATIONPROC>(GetProc("glBindAttribLocation"));

glBindBuffer = static_cast<_PFNGLBINDBUFFERPROC>(GetProc("glBindBuffer"));

glBindFramebuffer = static_cast<_PFNGLBINDFRAMEBUFFERPROC>(GetProc("glBindFramebuffer"));

glBindRenderbuffer = static_cast<_PFNGLBINDRENDERBUFFERPROC>(GetProc("glBindRenderbuffer"));

glBindTexture = static_cast<_PFNGLBINDTEXTUREPROC>(GetProc("glBindTexture"));

glBlendColor = static_cast<_PFNGLBLENDCOLORPROC>(GetProc("glBlendColor"));

glBlendEquation = static_cast<_PFNGLBLENDEQUATIONPROC>(GetProc("glBlendEquation"));

glBlendEquationSeparate = static_cast<_PFNGLBLENDEQUATIONSEPARATEPROC>(GetProc("glBlendEquationSeparate"));

glBlendFunc = static_cast<_PFNGLBLENDFUNCPROC>(GetProc("glBlendFunc"));

glBlendFuncSeparate = static_cast<_PFNGLBLENDFUNCSEPARATEPROC>(GetProc("glBlendFuncSeparate"));

glBufferData = static_cast<_PFNGLBUFFERDATAPROC>(GetProc("glBufferData"));

glBufferSubData = static_cast<_PFNGLBUFFERSUBDATAPROC>(GetProc("glBufferSubData"));

glCheckFramebufferStatus = static_cast<_PFNGLCHECKFRAMEBUFFERSTATUSPROC>(GetProc("glCheckFramebufferStatus"));

glClear = static_cast<_PFNGLCLEARPROC>(GetProc("glClear"));

glClearColor = static_cast<_PFNGLCLEARCOLORPROC>(GetProc("glClearColor"));

glClearDepthf = static_cast<_PFNGLCLEARDEPTHFPROC>(GetProc("glClearDepthf"));

glClearStencil = static_cast<_PFNGLCLEARSTENCILPROC>(GetProc("glClearStencil"));

glColorMask = static_cast<_PFNGLCOLORMASKPROC>(GetProc("glColorMask"));

glCompileShader = static_cast<_PFNGLCOMPILESHADERPROC>(GetProc("glCompileShader"));

glCompressedTexImage2D = static_cast<_PFNGLCOMPRESSEDTEXIMAGE2DPROC>(GetProc("glCompressedTexImage2D"));

glCompressedTexSubImage2D = static_cast<_PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC>(GetProc("glCompressedTexSubImage2D"));

glCopyTexImage2D = static_cast<_PFNGLCOPYTEXIMAGE2DPROC>(GetProc("glCopyTexImage2D"));

glCopyTexSubImage2D = static_cast<_PFNGLCOPYTEXSUBIMAGE2DPROC>(GetProc("glCopyTexSubImage2D"));

glCreateProgram = static_cast<_PFNGLCREATEPROGRAMPROC>(GetProc("glCreateProgram"));

glCreateShader = static_cast<_PFNGLCREATESHADERPROC>(GetProc("glCreateShader"));

glCullFace = static_cast<_PFNGLCULLFACEPROC>(GetProc("glCullFace"));

glDeleteBuffers = static_cast<_PFNGLDELETEBUFFERSPROC>(GetProc("glDeleteBuffers"));

glDeleteFramebuffers = static_cast<_PFNGLDELETEFRAMEBUFFERSPROC>(GetProc("glDeleteFramebuffers"));

glDeleteProgram = static_cast<_PFNGLDELETEPROGRAMPROC>(GetProc("glDeleteProgram"));

glDeleteRenderbuffers = static_cast<_PFNGLDELETERENDERBUFFERSPROC>(GetProc("glDeleteRenderbuffers"));

glDeleteShader = static_cast<_PFNGLDELETESHADERPROC>(GetProc("glDeleteShader"));

glDeleteTextures = static_cast<_PFNGLDELETETEXTURESPROC>(GetProc("glDeleteTextures"));

glDepthFunc = static_cast<_PFNGLDEPTHFUNCPROC>(GetProc("glDepthFunc"));

glDepthMask = static_cast<_PFNGLDEPTHMASKPROC>(GetProc("glDepthMask"));

glDepthRangef = static_cast<_PFNGLDEPTHRANGEFPROC>(GetProc("glDepthRangef"));

glDetachShader = static_cast<_PFNGLDETACHSHADERPROC>(GetProc("glDetachShader"));

glDisable = static_cast<_PFNGLDISABLEPROC>(GetProc("glDisable"));

glDisableVertexAttribArray = static_cast<_PFNGLDISABLEVERTEXATTRIBARRAYPROC>(GetProc("glDisableVertexAttribArray"));

glDrawArrays = static_cast<_PFNGLDRAWARRAYSPROC>(GetProc("glDrawArrays"));

glDrawElements = static_cast<_PFNGLDRAWELEMENTSPROC>(GetProc("glDrawElements"));

glEnable = static_cast<_PFNGLENABLEPROC>(GetProc("glEnable"));

glEnableVertexAttribArray = static_cast<_PFNGLENABLEVERTEXATTRIBARRAYPROC>(GetProc("glEnableVertexAttribArray"));

glFinish = static_cast<_PFNGLFINISHPROC>(GetProc("glFinish"));

glFlush = static_cast<_PFNGLFLUSHPROC>(GetProc("glFlush"));

glFramebufferRenderbuffer = static_cast<_PFNGLFRAMEBUFFERRENDERBUFFERPROC>(GetProc("glFramebufferRenderbuffer"));

glFramebufferTexture2D = static_cast<_PFNGLFRAMEBUFFERTEXTURE2DPROC>(GetProc("glFramebufferTexture2D"));

glFrontFace = static_cast<_PFNGLFRONTFACEPROC>(GetProc("glFrontFace"));

glGenBuffers = static_cast<_PFNGLGENBUFFERSPROC>(GetProc("glGenBuffers"));

glGenerateMipmap = static_cast<_PFNGLGENERATEMIPMAPPROC>(GetProc("glGenerateMipmap"));

glGenFramebuffers = static_cast<_PFNGLGENFRAMEBUFFERSPROC>(GetProc("glGenFramebuffers"));

glGenRenderbuffers = static_cast<_PFNGLGENRENDERBUFFERSPROC>(GetProc("glGenRenderbuffers"));

glGenTextures = static_cast<_PFNGLGENTEXTURESPROC>(GetProc("glGenTextures"));

glGetActiveAttrib = static_cast<_PFNGLGETACTIVEATTRIBPROC>(GetProc("glGetActiveAttrib"));

glGetActiveUniform = static_cast<_PFNGLGETACTIVEUNIFORMPROC>(GetProc("glGetActiveUniform"));

glGetAttachedShaders = static_cast<_PFNGLGETATTACHEDSHADERSPROC>(GetProc("glGetAttachedShaders"));

glGetAttribLocation = static_cast<_PFNGLGETATTRIBLOCATIONPROC>(GetProc("glGetAttribLocation"));

glGetBooleanv = static_cast<_PFNGLGETBOOLEANVPROC>(GetProc("glGetBooleanv"));

glGetBufferParameteriv = static_cast<_PFNGLGETBUFFERPARAMETERIVPROC>(GetProc("glGetBufferParameteriv"));

glGetError = static_cast<_PFNGLGETERRORPROC>(GetProc("glGetError"));

glGetFloatv = static_cast<_PFNGLGETFLOATVPROC>(GetProc("glGetFloatv"));

glGetFramebufferAttachmentParameteriv = static_cast<_PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC>(GetProc("glGetFramebufferAttachmentParameteriv"));

glGetIntegerv = static_cast<_PFNGLGETINTEGERVPROC>(GetProc("glGetIntegerv"));

glGetProgramiv = static_cast<_PFNGLGETPROGRAMIVPROC>(GetProc("glGetProgramiv"));

glGetProgramInfoLog = static_cast<_PFNGLGETPROGRAMINFOLOGPROC>(GetProc("glGetProgramInfoLog"));

glGetRenderbufferParameteriv = static_cast<_PFNGLGETRENDERBUFFERPARAMETERIVPROC>(GetProc("glGetRenderbufferParameteriv"));

glGetShaderiv = static_cast<_PFNGLGETSHADERIVPROC>(GetProc("glGetShaderiv"));

glGetShaderInfoLog = static_cast<_PFNGLGETSHADERINFOLOGPROC>(GetProc("glGetShaderInfoLog"));

glGetShaderPrecisionFormat = static_cast<_PFNGLGETSHADERPRECISIONFORMATPROC>(GetProc("glGetShaderPrecisionFormat"));

glGetShaderSource = static_cast<_PFNGLGETSHADERSOURCEPROC>(GetProc("glGetShaderSource"));

glGetString = static_cast<_PFNGLGETSTRINGPROC>(GetProc("glGetString"));

glGetTexParameterfv = static_cast<_PFNGLGETTEXPARAMETERFVPROC>(GetProc("glGetTexParameterfv"));

glGetTexParameteriv = static_cast<_PFNGLGETTEXPARAMETERIVPROC>(GetProc("glGetTexParameteriv"));

glGetUniformfv = static_cast<_PFNGLGETUNIFORMFVPROC>(GetProc("glGetUniformfv"));

glGetUniformiv = static_cast<_PFNGLGETUNIFORMIVPROC>(GetProc("glGetUniformiv"));

glGetUniformLocation = static_cast<_PFNGLGETUNIFORMLOCATIONPROC>(GetProc("glGetUniformLocation"));

glGetVertexAttribfv = static_cast<_PFNGLGETVERTEXATTRIBFVPROC>(GetProc("glGetVertexAttribfv"));

glGetVertexAttribiv = static_cast<_PFNGLGETVERTEXATTRIBIVPROC>(GetProc("glGetVertexAttribiv"));

glGetVertexAttribPointerv = static_cast<_PFNGLGETVERTEXATTRIBPOINTERVPROC>(GetProc("glGetVertexAttribPointerv"));

glHint = static_cast<_PFNGLHINTPROC>(GetProc("glHint"));

glIsBuffer = static_cast<_PFNGLISBUFFERPROC>(GetProc("glIsBuffer"));

glIsEnabled = static_cast<_PFNGLISENABLEDPROC>(GetProc("glIsEnabled"));

glIsFramebuffer = static_cast<_PFNGLISFRAMEBUFFERPROC>(GetProc("glIsFramebuffer"));

glIsProgram = static_cast<_PFNGLISPROGRAMPROC>(GetProc("glIsProgram"));

glIsRenderbuffer = static_cast<_PFNGLISRENDERBUFFERPROC>(GetProc("glIsRenderbuffer"));

glIsShader = static_cast<_PFNGLISSHADERPROC>(GetProc("glIsShader"));

glIsTexture = static_cast<_PFNGLISTEXTUREPROC>(GetProc("glIsTexture"));

glLineWidth = static_cast<_PFNGLLINEWIDTHPROC>(GetProc("glLineWidth"));

glLinkProgram = static_cast<_PFNGLLINKPROGRAMPROC>(GetProc("glLinkProgram"));

glPixelStorei = static_cast<_PFNGLPIXELSTOREIPROC>(GetProc("glPixelStorei"));

glPolygonOffset = static_cast<_PFNGLPOLYGONOFFSETPROC>(GetProc("glPolygonOffset"));

glReadPixels = static_cast<_PFNGLREADPIXELSPROC>(GetProc("glReadPixels"));

glReleaseShaderCompiler = static_cast<_PFNGLRELEASESHADERCOMPILERPROC>(GetProc("glReleaseShaderCompiler"));

glRenderbufferStorage = static_cast<_PFNGLRENDERBUFFERSTORAGEPROC>(GetProc("glRenderbufferStorage"));

glSampleCoverage = static_cast<_PFNGLSAMPLECOVERAGEPROC>(GetProc("glSampleCoverage"));

glScissor = static_cast<_PFNGLSCISSORPROC>(GetProc("glScissor"));

glShaderBinary = static_cast<_PFNGLSHADERBINARYPROC>(GetProc("glShaderBinary"));

glShaderSource = static_cast<_PFNGLSHADERSOURCEPROC>(GetProc("glShaderSource"));

glStencilFunc = static_cast<_PFNGLSTENCILFUNCPROC>(GetProc("glStencilFunc"));

glStencilFuncSeparate = static_cast<_PFNGLSTENCILFUNCSEPARATEPROC>(GetProc("glStencilFuncSeparate"));

glStencilMask = static_cast<_PFNGLSTENCILMASKPROC>(GetProc("glStencilMask"));

glStencilMaskSeparate = static_cast<_PFNGLSTENCILMASKSEPARATEPROC>(GetProc("glStencilMaskSeparate"));

glStencilOp = static_cast<_PFNGLSTENCILOPPROC>(GetProc("glStencilOp"));

glStencilOpSeparate = static_cast<_PFNGLSTENCILOPSEPARATEPROC>(GetProc("glStencilOpSeparate"));

glTexImage2D = static_cast<_PFNGLTEXIMAGE2DPROC>(GetProc("glTexImage2D"));

glTexParameterf = static_cast<_PFNGLTEXPARAMETERFPROC>(GetProc("glTexParameterf"));

glTexParameterfv = static_cast<_PFNGLTEXPARAMETERFVPROC>(GetProc("glTexParameterfv"));

glTexParameteri = static_cast<_PFNGLTEXPARAMETERIPROC>(GetProc("glTexParameteri"));

glTexParameteriv = static_cast<_PFNGLTEXPARAMETERIVPROC>(GetProc("glTexParameteriv"));

glTexSubImage2D = static_cast<_PFNGLTEXSUBIMAGE2DPROC>(GetProc("glTexSubImage2D"));

glUniform1f = static_cast<_PFNGLUNIFORM1FPROC>(GetProc("glUniform1f"));

glUniform1fv = static_cast<_PFNGLUNIFORM1FVPROC>(GetProc("glUniform1fv"));

glUniform1i = static_cast<_PFNGLUNIFORM1IPROC>(GetProc("glUniform1i"));

glUniform1iv = static_cast<_PFNGLUNIFORM1IVPROC>(GetProc("glUniform1iv"));

glUniform2f = static_cast<_PFNGLUNIFORM2FPROC>(GetProc("glUniform2f"));

glUniform2fv = static_cast<_PFNGLUNIFORM2FVPROC>(GetProc("glUniform2fv"));

glUniform2i = static_cast<_PFNGLUNIFORM2IPROC>(GetProc("glUniform2i"));

glUniform2iv = static_cast<_PFNGLUNIFORM2IVPROC>(GetProc("glUniform2iv"));

glUniform3f = static_cast<_PFNGLUNIFORM3FPROC>(GetProc("glUniform3f"));

glUniform3fv = static_cast<_PFNGLUNIFORM3FVPROC>(GetProc("glUniform3fv"));

glUniform3i = static_cast<_PFNGLUNIFORM3IPROC>(GetProc("glUniform3i"));

glUniform3iv = static_cast<_PFNGLUNIFORM3IVPROC>(GetProc("glUniform3iv"));

glUniform4f = static_cast<_PFNGLUNIFORM4FPROC>(GetProc("glUniform4f"));

glUniform4fv = static_cast<_PFNGLUNIFORM4FVPROC>(GetProc("glUniform4fv"));

glUniform4i = static_cast<_PFNGLUNIFORM4IPROC>(GetProc("glUniform4i"));

glUniform4iv = static_cast<_PFNGLUNIFORM4IVPROC>(GetProc("glUniform4iv"));

glUniformMatrix2fv = static_cast<_PFNGLUNIFORMMATRIX2FVPROC>(GetProc("glUniformMatrix2fv"));

glUniformMatrix3fv = static_cast<_PFNGLUNIFORMMATRIX3FVPROC>(GetProc("glUniformMatrix3fv"));

glUniformMatrix4fv = static_cast<_PFNGLUNIFORMMATRIX4FVPROC>(GetProc("glUniformMatrix4fv"));

glUseProgram = static_cast<_PFNGLUSEPROGRAMPROC>(GetProc("glUseProgram"));

glValidateProgram = static_cast<_PFNGLVALIDATEPROGRAMPROC>(GetProc("glValidateProgram"));

glVertexAttrib1f = static_cast<_PFNGLVERTEXATTRIB1FPROC>(GetProc("glVertexAttrib1f"));

glVertexAttrib1fv = static_cast<_PFNGLVERTEXATTRIB1FVPROC>(GetProc("glVertexAttrib1fv"));

glVertexAttrib2f = static_cast<_PFNGLVERTEXATTRIB2FPROC>(GetProc("glVertexAttrib2f"));

glVertexAttrib2fv = static_cast<_PFNGLVERTEXATTRIB2FVPROC>(GetProc("glVertexAttrib2fv"));

glVertexAttrib3f = static_cast<_PFNGLVERTEXATTRIB3FPROC>(GetProc("glVertexAttrib3f"));

glVertexAttrib3fv = static_cast<_PFNGLVERTEXATTRIB3FVPROC>(GetProc("glVertexAttrib3fv"));

glVertexAttrib4f = static_cast<_PFNGLVERTEXATTRIB4FPROC>(GetProc("glVertexAttrib4f"));

glVertexAttrib4fv = static_cast<_PFNGLVERTEXATTRIB4FVPROC>(GetProc("glVertexAttrib4fv"));

glVertexAttribPointer = static_cast<_PFNGLVERTEXATTRIBPOINTERPROC>(GetProc("glVertexAttribPointer"));

glViewport = static_cast<_PFNGLVIEWPORTPROC>(GetProc("glViewport"));

